services:
  postgres_container:
    build: ./postgres_container

    ports:
      - '5433:5432'

    environment:
      POSTGRES_PASSWORD: "admin"

    container_name: postgres_container

  etl_container:
    build: ./ETL_container


    volumes:
     - logs_vol:/app/logs
    stdin_open: true
    tty: true
    depends_on: 
      - postgres_container

    container_name: ETL_container


volumes:
  logs_vol: